apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-initdb-config
data:
  initdb.sql: |
    CREATE DATABASE IF NOT EXISTS {{ .Values.Ekube.Schema }};
    CREATE USER '{{ .Values.Ekube.User }}'@'%' IDENTIFIED BY '{{ .Values.Ekube.Pass }}';
    GRANT CREATE, INSERT, UPDATE, SELECT, DELETE ON {{ .Values.Ekube.Schema }}.* TO '{{ .Values.Ekube.User }}'@'%';
