apiVersion: v1
kind: Secret
metadata:
  name: {{ template "fullname" . }}
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ template "mysql.chart" . }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
  mysql-root-pass: {{ randAlphaNum 12 | b64enc | quote }}
  mysql-password: {{ randAlphaNum 12 | b64enc | quote }}
  mysql-replication-password: {{ randAlphaNum 12 | b64enc | quote }}
  mysql-user-name: {{ "user" | b64enc }}
  mysql-user-pass: {{ "password" | b64enc }}
