apiVersion: v1                    # API version
kind: Service                     # Type of kubernetes resource
metadata:
  name: mysql-app         # Name of the resource
  labels:                         # Labels that will be applied to the resource
    app: mysql-app
spec:
  ports:
    - port: 3306
  selector:                       # Selects any Pod with labels `app=mysql-app,tier=mysql`
    app: mysql-app
    tier: mysql
  clusterIP: None