apiVersion: v1                    # API version
kind: Service                     # Type of kubernetes resource
metadata:
  name: {{ include "fullname" . }}         # Name of the resource
  labels:                         # Labels that will be applied to the resource
    {{- include "labels" . | nindent 4 }}
spec:
  ports:
    - port: 3306
  selector:                       # Selects any Pod with labels `app=mysql-app,tier=mysql`
    {{- include "selectorLabels" . | nindent 4 }}
    tier: mysql
  clusterIP: None